[SYM-3635] Custom Strategy Quickstart
symopsio/sym-custom-strategy-quickstart pull request #1
Opened 2022-05-03 19:52 UTC by Arianna2028

This PR contains the contents required to get up and running with a custom access strategy. It should be apply-able and then immediately usable, though it doesn't actually do any real escalation.

2022-05-03 19:52 UTC, Arianna2028 commented
Current dependencies on/for this PR:
* main
  * **PR #1** <a href="https://app.graphite.dev/github/pr/symopsio/sym-custom-strategy-quickstart/1" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  (this PR)

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/symopsio/sym-custom-strategy-quickstart/1?utm_source=stack-comment).

2022-05-04 04:46 UTC, sym-andrewa requested changes
Noticed an issue with the strategy settings, plus a wording nitpick

2022-05-04 04:46 UTC, sym-andrewa commented on app/variables.tf
> +  description = "The error channel to use to surface Sym errors."
Nit: This wording seems a bit repetitive; perhaps something like "The Slack channel to use to surface Sym errors" might be better? (Also has the benefit of clarifying what's meant by "channel".)

2022-05-04 04:46 UTC, sym-andrewa commented on modules/custom-access-flow/main.tf
> +    api_token_secret = sym_secret.api_key.id
```suggestion
    secret_ids_json = jsonencode([sym_secret.api_key.id])
```

2022-05-04 04:46 UTC, sym-andrewa commented on modules/sym-runtime/variables.tf
> +  description = "The error channel to use to surface Sym errors."
Nit: Same here with respect to the wording of the description

2022-05-04 16:49 UTC, sym-andrewa approved these changes
yee

2022-05-04 19:06 UTC, merged